CREATE TABLE IF NOT EXISTS public.tasks (
    id UUID DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    type TEXT NOT NULL,
    room TEXT NOT NULL,
    description TEXT NOT NULL,
    status TEXT NOT NULL,
    reported_by TEXT NOT NULL,
    direction TEXT NOT NULL,
    image_base64 TEXT,
    read_by_admin BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    resolved_at TIMESTAMP WITH TIME ZONE
);

ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all for tasks" ON public.tasks;
CREATE POLICY "Enable all for tasks" ON public.tasks FOR ALL USING (true);

INSERT INTO public.tasks (room, description, status, reported_by, direction, type) VALUES
('101', 'Limpieza aires acondicionados', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('102', 'Limpieza aires acondicionados', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('103', 'Limpieza aires acondicionados', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('104', 'Limpieza aires acondicionados', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('105', 'Limpieza aires acondicionados', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('106', 'Limpieza aires acondicionados', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('201', 'Limpieza aires acondicionados', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('202', 'Limpieza aires acondicionados', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('203', 'Limpieza aires acondicionados', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('204', 'Limpieza aires acondicionados', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('205', 'Limpieza aires acondicionados', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('206', 'Limpieza aires acondicionados', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('301', 'Limpieza aires acondicionados', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('302', 'Limpieza aires acondicionados', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('303', 'Limpieza aires acondicionados', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('304', 'Limpieza aires acondicionados', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('305', 'Limpieza aires acondicionados', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('306', 'Limpieza aires acondicionados', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Cocina', 'Limpieza aires acondicionados', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('E500', 'Limpieza aires acondicionados', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('107', 'Limpieza aires acondicionados', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Loft', 'Limpieza aires acondicionados', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Casa', 'Limpieza aires acondicionados', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('206', 'Puerta principal 206 arrastra', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('107', 'Resanar puerta 107', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('loft', 'Colocar Antiderrapante con color desnivel loft', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('casa', 'Colocar focos área estacionamiento de casa', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Reparar mesa de centro de palapa', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('casa', 'Jaladera closet casa', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Mandar a reparar horno de microondas', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Reparación de cafeteras', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Foco depa Sr Rolando fundido', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Dos cámaras no se ven en sistema', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('casa', 'Colocar toallero lado baño principal casa', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('casa', 'Chapa puerta principal de casa. Cambiar', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego CENTRAL', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 2 de mar)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 304-306', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 2 de mar)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 301-303', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 2 de mar)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego jardín', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 2 de mar)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardineras afuera', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 2 de mar)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardinera alberca', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 2 de mar)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Secadora Industrial', 'Verificar limpieza filtros (APAGAR PASTILLAS LUZ) (mar, 4 de nov de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Lavadora Industrial', 'Verificar limpieza filtros (APAGAR PASTILLAS LUZ) (mar, 4 de nov de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Lavadoras pequeñas', 'Verificar limpieza filtros (APAGAR PASTILLAS LUZ) (mar, 4 de nov de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Secadoras pequeñas', 'Verificar limpieza filtros (APAGAR PASTILLAS LUZ) (mar, 4 de nov de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Limpieza atras de maquinas de lavandería', 'Verificar limpieza filtros (APAGAR PASTILLAS LUZ) (mar, 4 de nov de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('103', 'Cambio piso 103 baño (lun, 28 de jul de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Reportar luces de alumbrado público estén funcionando correctamente (mar, 5 de ago de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('100', 'Revisar y retocar Impermeabilizacion (lun 23 de mar)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('200', 'Revisar y retocar Impermeabilizacion (lun 23 de mar)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Casa', 'Revisar y retocar Impermeabilizacion (lun 23 de mar)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Lavandería y loft', 'Revisar y retocar Impermeabilizacion (lun 23 de mar)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Verificar quemadores de Secadora industrial (lun, 28 de abr de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'PEDIR GAS (mié 15 de abr)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Acomodo y limpieza de bodega y taller (lun, 19 de may de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('101', 'Cambio mangueras boylers de 1/2 a 3/4 (dom, 31 de ago de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('102', 'Cambio mangueras boylers de 1/2 a 3/4 (dom, 31 de ago de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('103', 'Cambio mangueras boylers de 1/2 a 3/4 (dom, 31 de ago de 2025)', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('104', 'Cambio mangueras boylers de 1/2 a 3/4 (dom, 31 de ago de 2025)', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('105', 'Cambio mangueras boylers de 1/2 a 3/4 (dom, 31 de ago de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('106', 'Cambio mangueras boylers de 1/2 a 3/4 (dom, 31 de ago de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Colocación de cemento blanco, cal con pintura en barda del vecino (mar, 15 de jul de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Instalar Electronivel sisterna azul, poner by Pass y poner pastilla para bomba', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Limpieza de tinacos (mar, 2 de sep de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('casa', 'Remplazo total de cuellos de cera de todos los baños de la casa (sáb, 30 de ago de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('casa', 'Manijas carpintería  casa y 107 (mar, 5 de ago de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Limpieza de registros eléctricos (IVAN-ELIHU) (antes de las lluvias) (mar, 1 de jun de 2027)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'PEDIR GAS (vie 1 de may)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('301', 'Apagador ventilador 301,105', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Checar plantas interiores', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('305', 'Resanar baño 305', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('204', 'Resanar baño 204', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('101', 'Apretar papelera de la 101 baño', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('503', 'Quitar tabla roca 503 13 /marzo', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('203', 'Ventilador 203 checar', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('306', 'Ventilador 306 esta lento', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Puerta de basurero. Checar chapa', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Colocar porta cigarros', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('102', 'Foco parte exterior pasillo 102', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('203', 'Fuga de la 203 tarja', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('103', 'Chapa reparación 103', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Ajustar porta escobas área patio de tendido', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Reparación de tendederos', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('506', 'Mezcladora floja 506', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('306', 'Mezcladora floja 306', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('306', 'Chapa floja 306', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('107', 'Cambio cuello de cera baño 107', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('203', '203 ventilador de sala se mueve mucho', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('301', 'Mezcladora 301 se mueve', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('106', '106 ventana atorada', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Reparación de pistola de hidrolavadora', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Chapa depa sr Rolando', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Colocar control ventilador de baño', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('casa', 'Mezcladora de casa esta floja', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('casa', 'Baño de casa de abajo checar focos', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Colocar maya a coladeras, dos exterior y área de jardín', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Reparación rociador area jardín alado de la alberca', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('103', 'Tablaroca Puertas de comunicación 103,106', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('107', 'Sanitario 107 reparación en tanque', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Silla blanca de comedor le falta tornillo a respaldo', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('107', 'Mezcladora 107 floja', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Quitar decoración navideña', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Checar secadora industrial. Ruido en baleros', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('303', 'Cono de coladera 303', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('107', 'Apagador 107 lavandería', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('206', '206 checar plafon baño', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('107', '107 tarja', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('103', 'Chapa floja 103', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Reparación de manija secadora pequeña', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('cocina', 'Reparación de 2 sillas de la cocina', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Verificación plaga en macetas', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('106', 'Seguro ventana 106', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('105', 'Foco fundido pasillo 105', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Reparación de locetas área de alberca exterior', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('102', 'Cono 102 regadera', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('104', 'Bambú 104 recamara principal despegado', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('cocina', 'Ventilador de cocina empleados', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('104', 'Cono baño 104', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('401', 'Cambio de ventilador 401', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('401', 'Cambiar chapa bodega 401', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('304', 'Foco fundido 304', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Cambiar electro nivel tinaco de recepción', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('304', 'Reparación de pieza refrigerador 304', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('306', '306 chapa floja', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('102', 'Tubo de boiler 102 pintar', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('107', 'Cespol 107', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('201', 'Cortina 201 suena', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('103', 'Cambio de lámpara de la 103 baño', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('205', 'Cespol 205', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Sapo baño mujeres', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('304', '304 fuga llave lavabo', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('401', 'Baño 401 siempre huele a drenaje', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('101', 'Foco fachada 101', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('106', 'Puerta 106 rechina', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Agregar Antiderrapantes al siguiente escalón y sellar detalles de alberca con cemento blanco', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('105', 'Mezcladora 105 cambiar', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Foco lado plafon recepción', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Plafon área de recepción', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('203', 'Lavabo cambiar mezcladora 203', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Instalación de dos focos lado jardinería de enemedio', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Pegar lámpara de area de alberca', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Secadora pequeña no enciende', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Reparación de tapa de lavadora pequeña', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Coladera regadera áreas publicas', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('203', 'Filtración patio de tendido 203', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('201', 'Foco lateral 201', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('302', '302 asiento de wc', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Limpieza de cebollas', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Reparación de cafetera', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('casa', 'Sellar ventana de la casa. Recamara king filtra cuando llueve', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('101', 'Foco fachada 101 no esta funcionando', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Checar cámaras qué no funcionan', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('loft', 'Reparación tres filtraciones por lluvias en loft', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Colocación de atrapolvos puertas blancas', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('301', 'Reparación de detalle de la 301.en piso de arriba', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('102', 'Chapa 102 checar', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('107', 'Chapa 107', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Cambio de foto celda lado recepción', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Colocar flor de mayo donde estaba el limonar', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Mantenimiento secadora chica', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Reparación piso área de alberca', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('202', '202 mezcladora', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('203', '203 cespol lavadero', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Termitas en palapas', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('201', '201 atrapolvo', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Colocación de trampas en pasillos para lagartijas', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('102', '102 fregadero tiene fuga', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('107', 'Foco fundido 107, pasillo e500', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('401', '401 no tiene atrapa polvo puerta lavandería', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('303', 'Mosquitero 303 roto', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Silla rota se dejó en el comedor', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('casa', 'Cambiar asiento wc de la casa', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('103', 'Quitar sarro ventilador 103. Cama king size', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('103', 'Pintura de aceite en parrilla refrigerador 103', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('101', 'Pintura en detalle de la 101 color blanco cerca de la cocina', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Cambio de fotocelda recepción', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Colocar tendederos en habitaciones', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Cambio de foco lámparas. Pasillo de enmedio', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('casa', 'Pintar tubo boyler casa', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('107', 'Refrigerador 107 tira agua', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Colocar antiderrapante en primer escalón de Alberca', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'Reparar tubo de bomba de sisterna azul', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('casa', 'Colocación 1 reflectores lado casa', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego CENTRAL', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 10 de nov de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 304-306', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 10 de nov de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 301-303', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 10 de nov de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego jardín', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 10 de nov de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardineras afuera', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 10 de nov de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardinera alberca', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 10 de nov de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego CENTRAL', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 8 de dic de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 304-306', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 8 de dic de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 301-303', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 8 de dic de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego jardín', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 8 de dic de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardineras afuera', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 8 de dic de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardinera alberca', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 8 de dic de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego CENTRAL', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 19 de ene)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 304-306', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 19 de ene)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 301-303', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 19 de ene)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego jardín', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 19 de ene)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardineras afuera', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 19 de ene)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardinera alberca', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 19 de ene)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego CENTRAL', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 29 de sep de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 304-306', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 29 de sep de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 301-303', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 29 de sep de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego jardín', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 29 de sep de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardineras afuera', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 29 de sep de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardinera alberca', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 29 de sep de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego CENTRAL', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 2 de feb)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 304-306', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 2 de feb)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 301-303', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 2 de feb)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego jardín', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 2 de feb)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardineras afuera', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 2 de feb)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardinera alberca', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 2 de feb)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego CENTRAL', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 16 de feb)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 304-306', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 16 de feb)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 301-303', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 16 de feb)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego jardín', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 16 de feb)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardineras afuera', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 16 de feb)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardinera alberca', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 16 de feb)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego CENTRAL', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 5 de ene)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 304-306', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 5 de ene)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 301-303', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 5 de ene)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego jardín', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 5 de ene)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardineras afuera', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 5 de ene)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardinera alberca', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun 5 de ene)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego CENTRAL', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 13 de oct de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 304-306', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 13 de oct de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 301-303', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 13 de oct de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego jardín', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 13 de oct de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardineras afuera', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 13 de oct de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardinera alberca', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 13 de oct de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego CENTRAL', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 24 de nov de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 304-306', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 24 de nov de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 301-303', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 24 de nov de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego jardín', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 24 de nov de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardineras afuera', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 24 de nov de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardinera alberca', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 24 de nov de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego CENTRAL', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 27 de oct de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 304-306', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 27 de oct de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 301-303', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 27 de oct de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego jardín', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 27 de oct de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardineras afuera', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 27 de oct de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardinera alberca', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 27 de oct de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego CENTRAL', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 22 de dic de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 304-306', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 22 de dic de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 301-303', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 22 de dic de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego jardín', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 22 de dic de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardineras afuera', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 22 de dic de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardinera alberca', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 22 de dic de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego CENTRAL', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 1 de sep de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 304-306', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 1 de sep de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 301-303', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 1 de sep de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego jardín', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 1 de sep de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardineras afuera', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 1 de sep de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardinera alberca', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 1 de sep de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego CENTRAL', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 15 de sep de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 304-306', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 15 de sep de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego 301-303', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 15 de sep de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Riego jardín', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 15 de sep de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardineras afuera', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 15 de sep de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Jardinera alberca', 'Verificar limpieza filtros RIEGOS (ROBERTO) (lun, 15 de sep de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Secadora Industrial', 'Verificar limpieza filtros (APAGAR PASTILLAS LUZ) (mar, 29 de jul de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Lavadora Industrial', 'Verificar limpieza filtros (APAGAR PASTILLAS LUZ) (mar, 29 de jul de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Lavadoras pequeñas', 'Verificar limpieza filtros (APAGAR PASTILLAS LUZ) (mar, 29 de jul de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Secadoras pequeñas', 'Verificar limpieza filtros (APAGAR PASTILLAS LUZ) (mar, 29 de jul de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Limpieza atras de maquinas de lavandería', 'Verificar limpieza filtros (APAGAR PASTILLAS LUZ) (mar, 29 de jul de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Secadora Industrial', 'Verificar limpieza filtros (APAGAR PASTILLAS LUZ) (lun, 3 de nov de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Lavadora Industrial', 'Verificar limpieza filtros (APAGAR PASTILLAS LUZ) (lun, 3 de nov de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Lavadoras pequeñas', 'Verificar limpieza filtros (APAGAR PASTILLAS LUZ) (lun, 3 de nov de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Secadoras pequeñas', 'Verificar limpieza filtros (APAGAR PASTILLAS LUZ) (lun, 3 de nov de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Limpieza atras de maquinas de lavandería', 'Verificar limpieza filtros (APAGAR PASTILLAS LUZ) (lun, 3 de nov de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Secadora Industrial', 'Verificar limpieza filtros (APAGAR PASTILLAS LUZ) (mar, 12 de ago de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Lavadora Industrial', 'Verificar limpieza filtros (APAGAR PASTILLAS LUZ) (mar, 12 de ago de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Lavadoras pequeñas', 'Verificar limpieza filtros (APAGAR PASTILLAS LUZ) (mar, 12 de ago de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Secadoras pequeñas', 'Verificar limpieza filtros (APAGAR PASTILLAS LUZ) (mar, 12 de ago de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Limpieza atras de maquinas de lavandería', 'Verificar limpieza filtros (APAGAR PASTILLAS LUZ) (mar, 12 de ago de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Secadora Industrial', 'Verificar limpieza filtros (APAGAR PASTILLAS LUZ) (mar, 26 de ago de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Lavadora Industrial', 'Verificar limpieza filtros (APAGAR PASTILLAS LUZ) (mar, 26 de ago de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Lavadoras pequeñas', 'Verificar limpieza filtros (APAGAR PASTILLAS LUZ) (mar, 26 de ago de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Secadoras pequeñas', 'Verificar limpieza filtros (APAGAR PASTILLAS LUZ) (mar, 26 de ago de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('Limpieza atras de maquinas de lavandería', 'Verificar limpieza filtros (APAGAR PASTILLAS LUZ) (mar, 26 de ago de 2025)', 'pendiente', 'Admin', 'admin_to_staff', 'mantenimiento'),
('106', '106 Checar cespol fregadero se tira mucha agua cuando se lavan trastes', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('203', 'Cambio mezcladora lavabo 203', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('202', 'Cambio mezcladora tarja 202', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'PEDIR GAS (jue 15 de ene)', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'PEDIR GAS (lun, 15 de sep de 2025)', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'PEDIR GAS (sáb, 15 de nov de 2025)', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'PEDIR GAS (mié, 15 de oct de 2025)', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'PEDIR GAS (dom 15 de mar)', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'PEDIR GAS (lun, 15 de dic de 2025)', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'PEDIR GAS (dom 15 de feb)', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'PEDIR GAS (mié, 1 de oct de 2025)', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'PEDIR GAS (dom 1 de feb)', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'PEDIR GAS (lun, 1 de dic de 2025)', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'PEDIR GAS (lun, 1 de sep de 2025)', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'PEDIR GAS (mié 1 de abr)', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'PEDIR GAS (jue 1 de ene)', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'PEDIR GAS (sáb, 1 de nov de 2025)', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento'),
('General', 'PEDIR GAS (dom 1 de mar)', 'resuelta', 'Admin', 'admin_to_staff', 'mantenimiento');
